version: '3.8'

services:
  db:
    image: postgres:15
    container_name: project_db
    environment:
      POSTGRES_DB: project_employee_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - project_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project_management_api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/project_employee_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - project_network

volumes:
  db-data:

networks:
  project_network:
    driver: bridge
