openapi: 3.0.1
info:
  title: Project Management API
  description: API for managing projects and their employees.
  version: 1.0.0
paths:
  /api/v1/projects:
    post:
      summary: Create a new project
      operationId: createProject
      tags:
        - Projects
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Bearer token for authorization
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectDto'
      responses:
        '201':
          description: Project successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '400':
          description: Bad request (validation errors or missing parameters)
        '401':
          description: Unauthorized (invalid or missing token)
    get:
      summary: Get all projects
      operationId: getAllProjects
      tags:
        - Projects
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Bearer token for authorization
          schema:
            type: string
      responses:
        '200':
          description: A list of all projects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
        '401':
          description: Unauthorized (invalid or missing token)
components:
  schemas:
    ProjectDto:
      type: object
      required:
        - nome
        - funcionarios
      properties:
        nome:
          type: string
          description: The name of the project
          example: "CCXP24"
        funcionarios:
          type: array
          items:
            $ref: '#/components/schemas/Employee'
          description: A list of employees in the project
    Project:
      type: object
      required:
        - id
        - nome
        - data_criacao
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the project
          example: "f047714f-3f23-4223-b709-de399174a634"
        nome:
          type: string
          description: The name of the project
          example: "CCXP24"
        data_criacao:
          type: string
          format: date-time
          description: The creation date of the project
          example: "2024-11-11T23:07:32.172"
        funcionarios:
          type: array
          items:
            $ref: '#/components/schemas/Employee'
          description: A list of employees associated with the project
    Employee:
      type: object
      required:
        - id
        - nome
        - cpf
        - email
        - salario
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the employee
          example: "0f4db84a-0eaf-4abf-b17c-31ba3bf90f25"
        nome:
          type: string
          description: Name of the employee
          example: "Caio"
        cpf:
          type: string
          description: CPF (Brazilian tax ID) of the employee
          example: "183.830.223-94"
        email:
          type: string
          format: email
          description: Email address of the employee
          example: "caio2@example.com"
        salario:
          type: number
          format: float
          description: The salary of the employee
          example: 19500.00