openapi: 3.0.1
info:
  title: API de Gerenciamento de Projetos
  description: API para criar projetos e gerenciar funcionários
  version: 1.0.0
paths:
  /api/v1/projetos:
    post:
      summary: Crie um novo projeto
      operationId: criarProject
      tags:
        - Projects
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Bearer token utilizado na autenticação
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjetoDto'
      responses:
        '201':
          description: Projeto foi criado com sucesso!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Projeto'
        '400':
          description: Bad request (erros de input ou parâmetros faltando)
        '401':
          description: Unauthorized (invalid or missing token)
    get:
      summary: Get all projects
      operationId: getAllProjects
      tags:
        - Projects
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Bearer token utilizado na autenticação
          schema:
            type: string
      responses:
        '200':
          description: Listagem de todos os projetos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Projeto'
        '401':
          description: Unauthorized (token inválido ou inexistente)
components:
  schemas:
    ProjetoDto:
      type: object
      required:
        - nome
        - funcionarios
      properties:
        nome:
          type: string
          description: O nome de um projeto
          example: "CCXP24"
        funcionarios:
          type: array
          items:
            $ref: '#/components/schemas/Employee'
          description: A lista de funcionários de um projeto
    Projeto:
      type: object
      required:
        - id
        - nome
        - data_criacao
      properties:
        id:
          type: string
          format: uuid
          description: Identificador único para o projeto
          example: "f047714f-3f23-4223-b709-de399174a634"
        nome:
          type: string
          description: O nome do projeto
          example: "CCXP24"
        data_criacao:
          type: string
          format: date-time
          description: A data de criação do projeto
          example: "2024-11-11T23:07:32.172"
        funcionarios:
          type: array
          items:
            $ref: '#/components/schemas/Employee'
          description: A lista de funcionários associados com o projeto
    Employee:
      type: object
      required:
        - id
        - nome
        - cpf
        - email
        - salario
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the employee
          example: "0f4db84a-0eaf-4abf-b17c-31ba3bf90f25"
        nome:
          type: string
          description: Nome do funcionário
          example: "Caio"
        cpf:
          type: string
          description: CPF do funcionário
          example: "183.830.223-94"
        email:
          type: string
          format: email
          description: Endereço de e-mail do funcionário
          example: "caio2@example.com"
        salario:
          type: number
          format: float
          description: O salário de um funcionário
          example: 19500.00